# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish executable
      working-directory: MarsRover
      run: dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true -o publish

    - name: List files in the publish folder
      run: |
        ls MarsRover/MarsRover/MarsRover/publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mars-rover
        path: MarsRover/MarsRover/MarsRover/publish/*
        retention-days: 7
